# Environment file for conda users
# Usage: conda env create -f environment.yml
name: xps-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11

  # Core scientific stack
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0

  # Data processing and analysis
  - scikit-learn>=1.0.0
  - h5py>=3.0.0
  - lmfit>=1.0.0

  # CLI and utilities
  - click>=8.0.0
  - tqdm>=4.60.0
  - pathlib  # Usually included in Python 3.4+

  # Jupyter ecosystem (optional but recommended for scientists)
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  - plotly>=5.0.0

  # Development tools (optional)
  - pytest>=6.0.0
  - pytest-cov>=2.12.0
  - mypy>=0.910
  - pre-commit>=2.15.0

  # Install via pip (not available in conda)
  - pip
  - pip:
    - ruff>=0.1.0
    - asteval>=1.0.0
    - uncertainties>=3.1.0
    # Note: The actual package will be installed via pip after environment creation
    # pip install -e . (when in the project directory)

# Post-installation instructions:
# 1. conda activate xps-analysis
# 2. cd path/to/xps-data-analysis
# 3. pip install -e ".[dev]"  # Install the actual package in development mode